/*
Agridence API

Testing GraphDataApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package arp_sdk_go_v1

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Agridence/arp-sdk-go-v1"
)

func Test_arp_sdk_go_v1_GraphDataApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GraphDataApiService GraphData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GraphDataApi.GraphData(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
