/*
Agridence API

Agridence

API version: v1.1
Contact: it@agridence.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arp_sdk_go_v1

import (
	"encoding/json"
)

// checks if the OfferPanelFilterGrade type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferPanelFilterGrade{}

// OfferPanelFilterGrade struct for OfferPanelFilterGrade
type OfferPanelFilterGrade struct {
	Id *int32 `json:"id,omitempty"`
	GradeCode *string `json:"grade_code,omitempty"`
	Country *string `json:"country,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewOfferPanelFilterGrade instantiates a new OfferPanelFilterGrade object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfferPanelFilterGrade() *OfferPanelFilterGrade {
	this := OfferPanelFilterGrade{}
	return &this
}

// NewOfferPanelFilterGradeWithDefaults instantiates a new OfferPanelFilterGrade object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfferPanelFilterGradeWithDefaults() *OfferPanelFilterGrade {
	this := OfferPanelFilterGrade{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OfferPanelFilterGrade) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterGrade) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OfferPanelFilterGrade) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OfferPanelFilterGrade) SetId(v int32) {
	o.Id = &v
}

// GetGradeCode returns the GradeCode field value if set, zero value otherwise.
func (o *OfferPanelFilterGrade) GetGradeCode() string {
	if o == nil || IsNil(o.GradeCode) {
		var ret string
		return ret
	}
	return *o.GradeCode
}

// GetGradeCodeOk returns a tuple with the GradeCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterGrade) GetGradeCodeOk() (*string, bool) {
	if o == nil || IsNil(o.GradeCode) {
		return nil, false
	}
	return o.GradeCode, true
}

// HasGradeCode returns a boolean if a field has been set.
func (o *OfferPanelFilterGrade) HasGradeCode() bool {
	if o != nil && !IsNil(o.GradeCode) {
		return true
	}

	return false
}

// SetGradeCode gets a reference to the given string and assigns it to the GradeCode field.
func (o *OfferPanelFilterGrade) SetGradeCode(v string) {
	o.GradeCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *OfferPanelFilterGrade) GetCountry() string {
	if o == nil || IsNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterGrade) GetCountryOk() (*string, bool) {
	if o == nil || IsNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *OfferPanelFilterGrade) HasCountry() bool {
	if o != nil && !IsNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *OfferPanelFilterGrade) SetCountry(v string) {
	o.Country = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OfferPanelFilterGrade) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterGrade) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OfferPanelFilterGrade) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OfferPanelFilterGrade) SetName(v string) {
	o.Name = &v
}

func (o OfferPanelFilterGrade) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferPanelFilterGrade) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: id is readOnly
	// skip: grade_code is readOnly
	// skip: country is readOnly
	// skip: name is readOnly
	return toSerialize, nil
}

type NullableOfferPanelFilterGrade struct {
	value *OfferPanelFilterGrade
	isSet bool
}

func (v NullableOfferPanelFilterGrade) Get() *OfferPanelFilterGrade {
	return v.value
}

func (v *NullableOfferPanelFilterGrade) Set(val *OfferPanelFilterGrade) {
	v.value = val
	v.isSet = true
}

func (v NullableOfferPanelFilterGrade) IsSet() bool {
	return v.isSet
}

func (v *NullableOfferPanelFilterGrade) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfferPanelFilterGrade(val *OfferPanelFilterGrade) *NullableOfferPanelFilterGrade {
	return &NullableOfferPanelFilterGrade{value: val, isSet: true}
}

func (v NullableOfferPanelFilterGrade) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfferPanelFilterGrade) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


