/*
Agridence API

Agridence

API version: v1
Contact: it@agridence.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arp_sdk_go_v1

import (
	"encoding/json"
)

// checks if the OfferPanelFilterList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferPanelFilterList200Response{}

// OfferPanelFilterList200Response struct for OfferPanelFilterList200Response
type OfferPanelFilterList200Response struct {
	Count int32 `json:"count"`
	Next NullableString `json:"next,omitempty"`
	Previous NullableString `json:"previous,omitempty"`
	Results []OfferPanelFilter `json:"results"`
}

// NewOfferPanelFilterList200Response instantiates a new OfferPanelFilterList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfferPanelFilterList200Response(count int32, results []OfferPanelFilter) *OfferPanelFilterList200Response {
	this := OfferPanelFilterList200Response{}
	this.Count = count
	this.Results = results
	return &this
}

// NewOfferPanelFilterList200ResponseWithDefaults instantiates a new OfferPanelFilterList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfferPanelFilterList200ResponseWithDefaults() *OfferPanelFilterList200Response {
	this := OfferPanelFilterList200Response{}
	return &this
}

// GetCount returns the Count field value
func (o *OfferPanelFilterList200Response) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterList200Response) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *OfferPanelFilterList200Response) SetCount(v int32) {
	o.Count = v
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OfferPanelFilterList200Response) GetNext() string {
	if o == nil || isNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OfferPanelFilterList200Response) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *OfferPanelFilterList200Response) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *OfferPanelFilterList200Response) SetNext(v string) {
	o.Next.Set(&v)
}
// SetNextNil sets the value for Next to be an explicit nil
func (o *OfferPanelFilterList200Response) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *OfferPanelFilterList200Response) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OfferPanelFilterList200Response) GetPrevious() string {
	if o == nil || isNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OfferPanelFilterList200Response) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *OfferPanelFilterList200Response) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *OfferPanelFilterList200Response) SetPrevious(v string) {
	o.Previous.Set(&v)
}
// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *OfferPanelFilterList200Response) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *OfferPanelFilterList200Response) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value
func (o *OfferPanelFilterList200Response) GetResults() []OfferPanelFilter {
	if o == nil {
		var ret []OfferPanelFilter
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterList200Response) GetResultsOk() ([]OfferPanelFilter, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *OfferPanelFilterList200Response) SetResults(v []OfferPanelFilter) {
	o.Results = v
}

func (o OfferPanelFilterList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferPanelFilterList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	toSerialize["results"] = o.Results
	return toSerialize, nil
}

type NullableOfferPanelFilterList200Response struct {
	value *OfferPanelFilterList200Response
	isSet bool
}

func (v NullableOfferPanelFilterList200Response) Get() *OfferPanelFilterList200Response {
	return v.value
}

func (v *NullableOfferPanelFilterList200Response) Set(val *OfferPanelFilterList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOfferPanelFilterList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOfferPanelFilterList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfferPanelFilterList200Response(val *OfferPanelFilterList200Response) *NullableOfferPanelFilterList200Response {
	return &NullableOfferPanelFilterList200Response{value: val, isSet: true}
}

func (v NullableOfferPanelFilterList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfferPanelFilterList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


