/*
Agridence API

Agridence

API version: v1
Contact: it@agridence.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arp_sdk_go_v1

import (
	"encoding/json"
)

// checks if the CompanyDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CompanyDetails{}

// CompanyDetails struct for CompanyDetails
type CompanyDetails struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
}

// NewCompanyDetails instantiates a new CompanyDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCompanyDetails(id int32, name string, type_ string) *CompanyDetails {
	this := CompanyDetails{}
	this.Id = id
	this.Name = name
	this.Type = type_
	return &this
}

// NewCompanyDetailsWithDefaults instantiates a new CompanyDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCompanyDetailsWithDefaults() *CompanyDetails {
	this := CompanyDetails{}
	return &this
}

// GetId returns the Id field value
func (o *CompanyDetails) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CompanyDetails) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CompanyDetails) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *CompanyDetails) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CompanyDetails) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CompanyDetails) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CompanyDetails) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CompanyDetails) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CompanyDetails) SetType(v string) {
	o.Type = v
}

func (o CompanyDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CompanyDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: id is readOnly
	// skip: name is readOnly
	// skip: type is readOnly
	return toSerialize, nil
}

type NullableCompanyDetails struct {
	value *CompanyDetails
	isSet bool
}

func (v NullableCompanyDetails) Get() *CompanyDetails {
	return v.value
}

func (v *NullableCompanyDetails) Set(val *CompanyDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCompanyDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCompanyDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCompanyDetails(val *CompanyDetails) *NullableCompanyDetails {
	return &NullableCompanyDetails{value: val, isSet: true}
}

func (v NullableCompanyDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCompanyDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


