/*
Agridence API

Agridence

API version: v1
Contact: it@agridence.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arp_sdk_go_v1

import (
	"encoding/json"
)

// checks if the OfferPanelFilterFactory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferPanelFilterFactory{}

// OfferPanelFilterFactory struct for OfferPanelFilterFactory
type OfferPanelFilterFactory struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	FactoryCode *string `json:"factory_code,omitempty"`
	Country *string `json:"country,omitempty"`
}

// NewOfferPanelFilterFactory instantiates a new OfferPanelFilterFactory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfferPanelFilterFactory() *OfferPanelFilterFactory {
	this := OfferPanelFilterFactory{}
	return &this
}

// NewOfferPanelFilterFactoryWithDefaults instantiates a new OfferPanelFilterFactory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfferPanelFilterFactoryWithDefaults() *OfferPanelFilterFactory {
	this := OfferPanelFilterFactory{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OfferPanelFilterFactory) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterFactory) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OfferPanelFilterFactory) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OfferPanelFilterFactory) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OfferPanelFilterFactory) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterFactory) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OfferPanelFilterFactory) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OfferPanelFilterFactory) SetName(v string) {
	o.Name = &v
}

// GetFactoryCode returns the FactoryCode field value if set, zero value otherwise.
func (o *OfferPanelFilterFactory) GetFactoryCode() string {
	if o == nil || isNil(o.FactoryCode) {
		var ret string
		return ret
	}
	return *o.FactoryCode
}

// GetFactoryCodeOk returns a tuple with the FactoryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterFactory) GetFactoryCodeOk() (*string, bool) {
	if o == nil || isNil(o.FactoryCode) {
		return nil, false
	}
	return o.FactoryCode, true
}

// HasFactoryCode returns a boolean if a field has been set.
func (o *OfferPanelFilterFactory) HasFactoryCode() bool {
	if o != nil && !isNil(o.FactoryCode) {
		return true
	}

	return false
}

// SetFactoryCode gets a reference to the given string and assigns it to the FactoryCode field.
func (o *OfferPanelFilterFactory) SetFactoryCode(v string) {
	o.FactoryCode = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *OfferPanelFilterFactory) GetCountry() string {
	if o == nil || isNil(o.Country) {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterFactory) GetCountryOk() (*string, bool) {
	if o == nil || isNil(o.Country) {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *OfferPanelFilterFactory) HasCountry() bool {
	if o != nil && !isNil(o.Country) {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *OfferPanelFilterFactory) SetCountry(v string) {
	o.Country = &v
}

func (o OfferPanelFilterFactory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferPanelFilterFactory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: id is readOnly
	// skip: name is readOnly
	// skip: factory_code is readOnly
	// skip: country is readOnly
	return toSerialize, nil
}

type NullableOfferPanelFilterFactory struct {
	value *OfferPanelFilterFactory
	isSet bool
}

func (v NullableOfferPanelFilterFactory) Get() *OfferPanelFilterFactory {
	return v.value
}

func (v *NullableOfferPanelFilterFactory) Set(val *OfferPanelFilterFactory) {
	v.value = val
	v.isSet = true
}

func (v NullableOfferPanelFilterFactory) IsSet() bool {
	return v.isSet
}

func (v *NullableOfferPanelFilterFactory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfferPanelFilterFactory(val *OfferPanelFilterFactory) *NullableOfferPanelFilterFactory {
	return &NullableOfferPanelFilterFactory{value: val, isSet: true}
}

func (v NullableOfferPanelFilterFactory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfferPanelFilterFactory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


