/*
Agridence API

Agridence

API version: v1
Contact: it@agridence.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package arp_sdk_go_v1

import (
	"encoding/json"
)

// checks if the OfferPanelFilterShippings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfferPanelFilterShippings{}

// OfferPanelFilterShippings struct for OfferPanelFilterShippings
type OfferPanelFilterShippings struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Incoterm *string `json:"incoterm,omitempty"`
}

// NewOfferPanelFilterShippings instantiates a new OfferPanelFilterShippings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfferPanelFilterShippings() *OfferPanelFilterShippings {
	this := OfferPanelFilterShippings{}
	return &this
}

// NewOfferPanelFilterShippingsWithDefaults instantiates a new OfferPanelFilterShippings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfferPanelFilterShippingsWithDefaults() *OfferPanelFilterShippings {
	this := OfferPanelFilterShippings{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OfferPanelFilterShippings) GetId() int32 {
	if o == nil || isNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterShippings) GetIdOk() (*int32, bool) {
	if o == nil || isNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OfferPanelFilterShippings) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OfferPanelFilterShippings) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OfferPanelFilterShippings) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterShippings) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OfferPanelFilterShippings) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OfferPanelFilterShippings) SetName(v string) {
	o.Name = &v
}

// GetIncoterm returns the Incoterm field value if set, zero value otherwise.
func (o *OfferPanelFilterShippings) GetIncoterm() string {
	if o == nil || isNil(o.Incoterm) {
		var ret string
		return ret
	}
	return *o.Incoterm
}

// GetIncotermOk returns a tuple with the Incoterm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfferPanelFilterShippings) GetIncotermOk() (*string, bool) {
	if o == nil || isNil(o.Incoterm) {
		return nil, false
	}
	return o.Incoterm, true
}

// HasIncoterm returns a boolean if a field has been set.
func (o *OfferPanelFilterShippings) HasIncoterm() bool {
	if o != nil && !isNil(o.Incoterm) {
		return true
	}

	return false
}

// SetIncoterm gets a reference to the given string and assigns it to the Incoterm field.
func (o *OfferPanelFilterShippings) SetIncoterm(v string) {
	o.Incoterm = &v
}

func (o OfferPanelFilterShippings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfferPanelFilterShippings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	// skip: id is readOnly
	// skip: name is readOnly
	// skip: incoterm is readOnly
	return toSerialize, nil
}

type NullableOfferPanelFilterShippings struct {
	value *OfferPanelFilterShippings
	isSet bool
}

func (v NullableOfferPanelFilterShippings) Get() *OfferPanelFilterShippings {
	return v.value
}

func (v *NullableOfferPanelFilterShippings) Set(val *OfferPanelFilterShippings) {
	v.value = val
	v.isSet = true
}

func (v NullableOfferPanelFilterShippings) IsSet() bool {
	return v.isSet
}

func (v *NullableOfferPanelFilterShippings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfferPanelFilterShippings(val *OfferPanelFilterShippings) *NullableOfferPanelFilterShippings {
	return &NullableOfferPanelFilterShippings{value: val, isSet: true}
}

func (v NullableOfferPanelFilterShippings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfferPanelFilterShippings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


